package org.alfasoftware.astra.core.refactoring.javapattern.performance;

import static org.junit.Assert.assertEquals;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.stream.Collectors;

import org.alfasoftware.astra.core.refactoring.AbstractRefactorTest;
import org.alfasoftware.astra.core.refactoring.UseCase;
import org.alfasoftware.astra.core.refactoring.operations.javapattern.JavaPatternASTOperation;
import org.alfasoftware.astra.core.utils.ASTOperation;
import org.alfasoftware.astra.core.utils.AstraCore;
import org.alfasoftware.astra.core.utils.AstraUtils;
import org.alfasoftware.astra.core.utils.ClassVisitor;
import org.eclipse.jdt.core.dom.ASTParser;
import org.eclipse.jdt.core.dom.CompilationUnit;
import org.eclipse.jdt.core.dom.FileASTRequestor;
import org.eclipse.jdt.core.dom.rewrite.ASTRewrite;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;

/**
 * Measures the performance of processing {@link JavaPatternASTOperation}s, over example source files generated by
 * {@link PerformanceExampleGenerator}.
 *
 * <p>Two scenarios are measured:
 * <ul>
 *   <li>"api-migration": three patterns migrating legacy APIs, whose method names only appear in a minority of files,</li>
 *   <li>"jdk-idioms": two patterns replacing JDK idioms, whose method names appear in almost every file.</li>
 * </ul>
 * For each scenario, two timings are taken:
 * <ul>
 *   <li>end-to-end: {@link AstraCore#run(String, UseCase)} over a fresh copy of the example files,
 *       i.e. reading, parsing, matching, rewriting and saving files,</li>
 *   <li>matching: running the operations against every node of pre-parsed compilation units, with AstraCore's
 *       {@link AstraCore#runOperations(Set, CompilationUnit)}. This isolates the cost of matching from the (much
 *       larger) cost of parsing.</li>
 * </ul>
 * Each timing also checks that the expected files, and only those, were refactored, and reports a digest of the
 * output, so that runs before and after a change can be checked to produce identical output.
 *
 * <p>By default this runs as a quick functional test over a few example files. To measure performance, run:
 * <pre>
 * mvn -pl astra-core test -Dtest=TestJavaPatternPerformance -Dastra.performance=true "-DargLine=-Xms2g -Xmx2g -XX:+AlwaysPreTouch"
 * </pre>
 * A fixed size, pre-touched heap avoids most of the run to run variation caused by the heap being resized.
 * This uses 400 example files, 3 warmup iterations and 8 measured iterations, with the operations applied
 * on a single thread. These can be changed with {@code -Dastra.performance.files},
 * {@code -Dastra.performance.warmup}, {@code -Dastra.performance.iterations} and
 * {@code -Dastra.performance.parallelism}. Results are printed, and written to
 * {@code target/java-pattern-performance/<scenario>.properties}.
 */
public class TestJavaPatternPerformance extends AbstractRefactorTest {

  private static final boolean PERFORMANCE_MODE = Boolean.getBoolean("astra.performance");
  private static final int FILES = Integer.getInteger("astra.performance.files", PERFORMANCE_MODE ? 400 : 20);
  private static final int WARMUP_ITERATIONS = Integer.getInteger("astra.performance.warmup", PERFORMANCE_MODE ? 3 : 0);
  private static final int MEASURED_ITERATIONS = Integer.getInteger("astra.performance.iterations", PERFORMANCE_MODE ? 8 : 1);
  private static final int PARALLELISM = Integer.getInteger("astra.performance.parallelism", 1);

  private static final String PATTERN_DIRECTORY = TEST_EXAMPLES + "/" + TestJavaPatternPerformance.class.getPackageName().replace('.', '/');
  private static final Path RESULTS_DIRECTORY = Path.of("target", "java-pattern-performance");

  private static PerformanceExampleGenerator examples;
  private static Level originalAstraCoreLogLevel;

  private Path tempDir;


  @BeforeClass
  public static void setUpClass() {
    examples = PerformanceExampleGenerator.generate(FILES);
    // AstraCore logs progress for every percent of the files processed, which would bury the results
    Logger astraCoreLogger = (Logger) LoggerFactory.getLogger(AstraCore.class);
    originalAstraCoreLogLevel = astraCoreLogger.getLevel();
    astraCoreLogger.setLevel(Level.WARN);
  }


  @AfterClass
  public static void tearDownClass() {
    ((Logger) LoggerFactory.getLogger(AstraCore.class)).setLevel(originalAstraCoreLogLevel);
  }


  @Before
  public void setUp() throws IOException {
    tempDir = Files.createTempDirectory("astra-java-pattern-performance-test");
  }


  @After
  public void tearDown() throws IOException {
    Files.walk(tempDir)
        .sorted(Comparator.reverseOrder())
        .forEach(path -> path.toFile().delete());
  }


  /**
   * Three patterns migrating legacy APIs ({@link LegacyCacheLookupPattern}, {@link MoneyConstructorPattern} and
   * {@link LegacyCacheStorePattern}), whose method and type names only appear in a minority of the example files.
   */
  @Test
  public void testApiMigrationPerformance() throws Exception {
    measure(new Scenario(
        "api-migration",
        Arrays.asList(LegacyCacheLookupPattern.class, MoneyConstructorPattern.class, LegacyCacheStorePattern.class),
        examples.getApiMigrationFileCount(),
        Arrays.asList("cache.lookup(", "new Money(", "cache.store(key, String.valueOf("),
        Arrays.asList("registry.lookup(", "cache.store(key, text)", "cache.put(key, text)", "Money.of(count, \"USD\")")));
  }


  /**
   * Two pattern files replacing JDK idioms ({@link StringIsEmptyPattern} and {@link MapContainsKeyPattern}),
   * whose method names appear in almost every example file.
   */
  @Test
  public void testJdkIdiomsPerformance() throws Exception {
    measure(new Scenario(
        "jdk-idioms",
        Arrays.asList(StringIsEmptyPattern.class, MapContainsKeyPattern.class),
        examples.getJdkIdiomFileCount(),
        Arrays.asList(".length() == 0", ".equals(\"\")", ".keySet().contains("),
        Arrays.asList("text.length() > count", "upper.equals(key)", "ids.contains(count)", "tokens.length == 0")));
  }


  private void measure(Scenario scenario) throws Exception {
    Set<ASTOperation> operations = new LinkedHashSet<>();
    for (Class<?> pattern : scenario.patterns) {
      operations.add(new JavaPatternASTOperation(Path.of(PATTERN_DIRECTORY, pattern.getSimpleName() + ".java"), new String[] {TEST_SOURCE}));
    }
    Path directory = Files.createDirectory(tempDir.resolve(scenario.name));

    // End-to-end: AstraCore.run over a fresh copy of the example files for every iteration
    UseCase useCase = new UseCase() {
      @Override
      public Set<? extends ASTOperation> getOperations() {
        return operations;
      }

      @Override
      public String[] getSources() {
        return new String[] {TEST_SOURCE};
      }

      @Override
      public int getParallelism() {
        return PARALLELISM;
      }
    };
    List<Long> endToEndTimings = new ArrayList<>();
    String endToEndDigest = null;
    for (int iteration = 0; iteration < WARMUP_ITERATIONS + MEASURED_ITERATIONS; iteration++) {
      examples.writeTo(directory);
      System.gc();
      long start = System.nanoTime();
      AstraCore.run(directory.toString(), useCase);
      long elapsed = System.nanoTime() - start;
      if (iteration >= WARMUP_ITERATIONS) {
        endToEndTimings.add(elapsed);
      }
      endToEndDigest = verifyOutput(scenario, examples.readFrom(directory), "end-to-end");
    }

    // Matching: AstraCore's runOperations over pre-parsed compilation units
    examples.writeTo(directory);
    Map<String, CompilationUnit> compilationUnits = parse(directory);
    List<Long> matchingTimings = new ArrayList<>();
    for (int iteration = 0; iteration < WARMUP_ITERATIONS + MEASURED_ITERATIONS; iteration++) {
      System.gc();
      long start = System.nanoTime();
      for (CompilationUnit compilationUnit : compilationUnits.values()) {
        runOperations(operations, compilationUnit);
      }
      long elapsed = System.nanoTime() - start;
      if (iteration >= WARMUP_ITERATIONS) {
        matchingTimings.add(elapsed);
      }
    }
    long operationInvocations = 0;
    Map<String, String> matchingOutput = new TreeMap<>();
    for (Map.Entry<String, CompilationUnit> entry : compilationUnits.entrySet()) {
      ClassVisitor visitor = new ClassVisitor();
      entry.getValue().accept(visitor);
      operationInvocations += (long) visitor.getVisitedNodes().size() * operations.size();
      String relativePath = directory.relativize(Path.of(entry.getKey())).toString();
      String source = examples.getFiles().get(relativePath);
      matchingOutput.put(relativePath, AstraUtils.makeChangesFromAST(source, runOperations(operations, entry.getValue())));
    }
    verifyOutput(scenario, matchingOutput, "matching");

    report(scenario, operations.size(), endToEndTimings, endToEndDigest, matchingTimings, operationInvocations);
  }


  /**
   * Checks that exactly the expected files were refactored, that every match was replaced,
   * and that none of the near misses were.
   *
   * @return a digest of the output
   */
  private static String verifyOutput(Scenario scenario, Map<String, String> output, String timing) {
    Map<String, String> input = examples.getFiles();
    long changedFiles = output.entrySet().stream().filter(file -> ! file.getValue().equals(input.get(file.getKey()))).count();
    assertEquals(scenario.name + " " + timing + ": files changed", scenario.expectedChangedFiles, changedFiles);
    for (String marker : scenario.replacedMarkers) {
      assertEquals(scenario.name + " " + timing + ": occurrences of [" + marker + "] after refactoring", 0, occurrences(output, marker));
    }
    for (String marker : scenario.nearMissMarkers) {
      assertEquals(scenario.name + " " + timing + ": occurrences of near miss [" + marker + "] after refactoring",
          occurrences(input, marker), occurrences(output, marker));
    }
    return PerformanceExampleGenerator.digest(output);
  }


  private static int occurrences(Map<String, String> files, String marker) {
    int count = 0;
    for (String content : files.values()) {
      for (int index = content.indexOf(marker); index >= 0; index = content.indexOf(marker, index + marker.length())) {
        count++;
      }
    }
    return count;
  }


  /**
   * Parses the example files with bindings, using a single batch parser, as AstraCore does.
   *
   * @return compilation units keyed by absolute path
   */
  private static Map<String, CompilationUnit> parse(Path directory) {
    String[] paths = examples.getFiles().keySet().stream()
        .map(relativePath -> directory.resolve(relativePath).toAbsolutePath().normalize().toString())
        .toArray(String[]::new);
    String[] encodings = new String[paths.length];
    Arrays.fill(encodings, StandardCharsets.UTF_8.name());
    Map<String, CompilationUnit> compilationUnits = new TreeMap<>();
    ASTParser parser = AstraUtils.createBatchParser(new String[] {TEST_SOURCE}, new String[0]);
    parser.createASTs(paths, encodings, new String[0], new FileASTRequestor() {
      @Override
      public void acceptAST(String sourceFilePath, CompilationUnit compilationUnit) {
        compilationUnit.recordModifications();
        compilationUnits.put(sourceFilePath, compilationUnit);
      }
    }, null);
    assertEquals("parsed compilation units", paths.length, compilationUnits.size());
    return compilationUnits;
  }


  /**
   * Runs every operation against every node of the compilation unit, using AstraCore's own
   * {@link AstraCore#runOperations(Set, CompilationUnit)}.
   */
  private static ASTRewrite runOperations(Set<? extends ASTOperation> operations, CompilationUnit compilationUnit) {
    return AstraCoreOperations.run(operations, compilationUnit);
  }


  /**
   * Gives the benchmark access to AstraCore's protected methods.
   */
  private static final class AstraCoreOperations extends AstraCore {
    private static ASTRewrite run(Set<? extends ASTOperation> operations, CompilationUnit compilationUnit) {
      return runOperations(operations, compilationUnit);
    }
  }


  private static void report(Scenario scenario, int operationCount, List<Long> endToEndTimings, String digest,
      List<Long> matchingTimings, long operationInvocations) throws IOException {
    double matchingMedian = median(matchingTimings);
    List<String> lines = new ArrayList<>();
    lines.add(String.format(Locale.ROOT, "scenario=%s", scenario.name));
    lines.add(String.format(Locale.ROOT, "files=%d", examples.getFileCount()));
    lines.add(String.format(Locale.ROOT, "filesChanged=%d", scenario.expectedChangedFiles));
    lines.add(String.format(Locale.ROOT, "operations=%d", operationCount));
    lines.add(String.format(Locale.ROOT, "parallelism=%d", PARALLELISM));
    lines.add(String.format(Locale.ROOT, "warmupIterations=%d", WARMUP_ITERATIONS));
    lines.add(String.format(Locale.ROOT, "measuredIterations=%d", MEASURED_ITERATIONS));
    lines.add(String.format(Locale.ROOT, "endToEndMedianMs=%.1f", millis(median(endToEndTimings))));
    lines.add(String.format(Locale.ROOT, "endToEndMinMs=%.1f", millis(Collections.min(endToEndTimings))));
    lines.add(String.format(Locale.ROOT, "endToEndMaxMs=%.1f", millis(Collections.max(endToEndTimings))));
    lines.add(String.format(Locale.ROOT, "matchingMedianMs=%.1f", millis(matchingMedian)));
    lines.add(String.format(Locale.ROOT, "matchingMinMs=%.1f", millis(Collections.min(matchingTimings))));
    lines.add(String.format(Locale.ROOT, "matchingMaxMs=%.1f", millis(Collections.max(matchingTimings))));
    lines.add(String.format(Locale.ROOT, "operationInvocations=%d", operationInvocations));
    lines.add(String.format(Locale.ROOT, "matchingNanosPerInvocation=%.1f", matchingMedian / operationInvocations));
    lines.add(String.format(Locale.ROOT, "outputDigest=%s", digest));
    lines.add("endToEndTimingsMs=" + formatMillis(endToEndTimings));
    lines.add("matchingTimingsMs=" + formatMillis(matchingTimings));

    StringBuilder printed = new StringBuilder(System.lineSeparator())
        .append("=== JavaPattern performance: ").append(scenario.name).append(" ===").append(System.lineSeparator());
    lines.forEach(line -> printed.append(line).append(System.lineSeparator()));
    System.out.println(printed);

    Files.createDirectories(RESULTS_DIRECTORY);
    Files.write(RESULTS_DIRECTORY.resolve(scenario.name + ".properties"), lines, StandardCharsets.UTF_8);
  }


  private static double median(List<Long> timings) {
    List<Long> sorted = new ArrayList<>(timings);
    Collections.sort(sorted);
    int middle = sorted.size() / 2;
    return sorted.size() % 2 == 1 ? sorted.get(middle) : (sorted.get(middle - 1) + sorted.get(middle)) / 2.0;
  }


  private static double millis(double nanos) {
    return nanos / 1_000_000.0;
  }


  private static String formatMillis(List<Long> timings) {
    return timings.stream().map(timing -> String.format(Locale.ROOT, "%.0f", millis(timing))).collect(Collectors.joining(","));
  }


  private static final class Scenario {
    private final String name;
    private final List<Class<?>> patterns;
    private final long expectedChangedFiles;
    /** Text which only appears in code the patterns should match, so should no longer appear after refactoring. */
    private final List<String> replacedMarkers;
    /** Text which only appears in code the patterns should not match, so should be unchanged by refactoring. */
    private final List<String> nearMissMarkers;

    private Scenario(String name, List<Class<?>> patterns, long expectedChangedFiles, List<String> replacedMarkers,
        List<String> nearMissMarkers) {
      this.name = name;
      this.patterns = patterns;
      this.expectedChangedFiles = expectedChangedFiles;
      this.replacedMarkers = replacedMarkers;
      this.nearMissMarkers = nearMissMarkers;
    }
  }
}
